### PR TITLE
Improved performance, fixed bug for strands visualization menu.

### LINKED ISSUE #291: Seasonality

### PR DESCRIPTION
**Pull request by edisonlee0212**

### CODE REVIEW

File: EvoEngine_Plugins/EcoSysLab/src/DynamicStrandsVisualization.cpp [hunk 1]
```diff
@@ -9,7 +9,7 @@ bool DynamicStrands::VisualizationParameters::OnInspect(const std::shared_ptr<Ed
   if (render_segments) {
     if (ImGui::Combo(
             "Segment mode",
-            {"Default", "Segment color", "Group index", "Boundary distance", "Strength", "Shear/Strain strain",
```
Comment (edisonlee0212) [inline EvoEngine_Plugins/EcoSysLab/src/DynamicStrandsVisualization.cpp:12]: @Jango6324 I fixed it here.

**Review by EvoEngine-Admin — APPROVED** [review]
